name: purz

services:
  database:
    container_name: database
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: purz
    ports:
      - "54323:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data
